# Text To Speech (TTS)


In [ ]:
from huggingface_hub import login
token = "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"
print("Hugging Face logging")
login(token)

Hugging Face logging


In [ ]:
import torch
device =  ( "cpu")
print(f"Usando dispositivo: {device}")

Usando dispositivo: cpu


In [ ]:
!pip install datasets

## Generación de audio con speaker embeddings default

In [ ]:
from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan
import torchaudio
import torch

# Configuración
model_name = "microsoft/speecht5_tts"  # Modelo SpeechT5 para TTS

# Cargar el modelo, el procesador y el vocoder
processor = SpeechT5Processor.from_pretrained(model_name)
model = SpeechT5ForTextToSpeech.from_pretrained(model_name, cache_dir="./models/speecht5_tts")
vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan", cache_dir="./models/speecht5_hifigan")

def text_to_speech(text, processor, model, vocoder, speaker_embeddings=torch.zeros((1, 512)), output_file="./output/output.wav"):
    global device
    # Procesar el texto
    inputs = processor(text=text, return_tensors="pt")

    # Generar el embedding de audio
    with torch.no_grad():
        speech = model.generate_speech(inputs["input_ids"], speaker_embeddings=speaker_embeddings).to(device)

    # Usar el vocoder para generar el audio final
    with torch.no_grad():
        audio = vocoder(speech).to(device)

    # Ajustar el tensor para que sea compatible con torchaudio (formato 2D)
    audio = audio.squeeze(0).unsqueeze(0)
    if output_file is not None:
        # Guardar el audio generado
        torchaudio.save(output_file, audio, sample_rate=16000)  # 16000 es la tasa de muestreo
        print(f"Audio guardado en {output_file}")
    return audio

2025-01-24 10:52:39.003263: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-24 10:52:39.011237: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1737715959.019979    3190 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1737715959.022600    3190 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-24 10:52:39.032144: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [ ]:
# Configuración
model_name = "microsoft/speecht5_tts"  # Modelo SpeechT5 para TTS

# Cargar el modelo, el procesador y el vocoder
processor = SpeechT5Processor.from_pretrained(model_name)
model = SpeechT5ForTextToSpeech.from_pretrained(model_name)
vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan")

In [ ]:
texto = "this is a generated text"
text_to_speech(text=texto,processor=processor, model=model, vocoder=vocoder, output_file="./audio_generado-es100.wav")

Audio guardado en ./audio_generado-es100.wav


tensor([[ 0.0003, -0.0004, -0.0001,  ...,  0.0077,  0.0096, -0.0202]])

## Generación de audio con speaker embeddings personalizados

In [ ]:
from datasets import load_dataset

# Cargar embeddings del dataset de voz
embeddings_dataset = load_dataset("Matthijs/cmu-arctic-xvectors", split="validation")
# Seleccionar un embedding específico (ajusta el índice según el dataset)
speaker_embeddings = torch.tensor(embeddings_dataset[500]["xvector"]).unsqueeze(0)

texto = "this is a generated text"
text_to_speech(text=texto,processor=processor, model=model, vocoder=vocoder, speaker_embeddings=speaker_embeddings, output_file="./audio_generado.wav")

Audio guardado en ./audio_generado.wav


tensor([[-0.0014, -0.0020, -0.0017,  ..., -0.0166,  0.0354,  0.0239]])

#### Tarea TTSB1

Generar distintos audios usando diferentes embeddings del dataset

In [ ]:
import random

# TODO: cambiar el numero del embedding del dataset para ver distintas generaciones, por ejemplo 5, para ello puede usar random_embedding = random.randint(1, 7500)


Audio guardado en ./audio_generado-es-0_42.wav
Audio guardado en ./audio_generado-es-1_6705.wav
Audio guardado en ./audio_generado-es-2_6048.wav
Audio guardado en ./audio_generado-es-3_5066.wav
Audio guardado en ./audio_generado-es-4_5734.wav


### Reproducción del audio en lugar de alamacenarlo

In [ ]:
import IPython.display as ipd
import torch

speaker_embeddings = torch.tensor(embeddings_dataset[7930]["xvector"]).unsqueeze(0)

texto = "this is a generated text"
audio = text_to_speech(text=texto,processor=processor, model=model, vocoder=vocoder, speaker_embeddings=speaker_embeddings, output_file=None)
audio_np = audio.numpy().squeeze()
ipd.display(ipd.Audio(audio_np, rate=16000))

## Generación de audio con speaker embeddings personalizados a partir de fichero wav

In [ ]:
from datasets import Audio
# Cargar el dataset personalizado
dataset = load_dataset("mozilla-foundation/common_voice_11_0", "es", split="test", cache_dir="./data/common_voice", trust_remote_code=True, streaming=True)
dataset = dataset.cast_column("audio", Audio(sampling_rate=16000))


In [ ]:
def filter_dataset(batch):
    return batch["client_id"] == "0a041928afd5c85b769b7aaafe7202013aa48b0a995bbb55c8ff5e6c76c9886a5c739f97ee85325f5ffa678576c81f0f9f038dd36428c69726934739e466cad8"

dataset = dataset.filter(filter_dataset)

In [ ]:
print(dataset)

IterableDataset({
    features: ['client_id', 'path', 'audio', 'sentence', 'up_votes', 'down_votes', 'age', 'gender', 'accent', 'locale', 'segment'],
    num_shards: 1
})


In [ ]:
from speechbrain.pretrained import SpeakerRecognition

embedding_model = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-xvect-voxceleb", run_opts={"device": device})

data = []
for item in dataset:
    data.append(item)
audio_entry = data[0]["audio"]

if "array" in audio_entry and "sampling_rate" in audio_entry:

    waveform = torch.tensor(audio_entry["array"], dtype=torch.float32).unsqueeze(0)
    sampling_rate = audio_entry["sampling_rate"]
else:
    import torchaudio
    audio_path = audio_entry["path"]
    waveform, sampling_rate = torchaudio.load(audio_path)

# generar speaker embedding
with torch.no_grad():
    speaker_embeddings = embedding_model.encode_batch(waveform).squeeze(0)
    texto = "Esto es un texto generado"
    text_to_speech(text=texto,processor=processor, model=model, vocoder=vocoder, speaker_embeddings=speaker_embeddings, output_file="./audio_generado-mozilla.wav")

INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
/tmp/ipykernel_3190/2517397696.py:1: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import SpeakerRecognition
INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch custom.py: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch embedding_model.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetchin

Audio guardado en ./audio_generado-mozilla.wav


#### Incrementando el numero de muestras

In [ ]:
from datasets import Audio
dataset = load_dataset("mozilla-foundation/common_voice_11_0", "es", split="test", cache_dir="./data/common_voice",trust_remote_code=True, streaming=True)
dataset = dataset.cast_column("audio", Audio(sampling_rate=16000))

In [ ]:
dataset = dataset.filter(lambda example: "España: Centro-Sur peninsular" in example["accent"] and "female" in example["gender"] )


In [ ]:
import numpy as np

def get_average_embedding(dataset, embedding_model):
    global device
    embeddings = []
    for entry in dataset:
        audio_entry = entry["audio"]
        if "array" in audio_entry and "sampling_rate" in audio_entry:
            waveform = torch.tensor(audio_entry["array"], dtype=torch.float32).unsqueeze(0)
        else:
            waveform, _ = torchaudio.load(audio_entry["path"])
        with torch.no_grad():
            embedding = embedding_model.encode_batch(waveform).squeeze(0).numpy()
            embeddings.append(embedding)
    embeddings = np.array(embeddings)  # Convertir a un numpy array para mejor manejo
    return torch.tensor(embeddings.mean(axis=0)).unsqueeze(0)


In [ ]:
# Cargar el modelo de reconocimiento de hablantes
embedding_model = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-xvect-voxceleb", run_opts={"device": device})

# Generar embedding promedio
speaker_embeddings = get_average_embedding(dataset, embedding_model)
# Ajustar dimensiones de speaker_embeddings
if speaker_embeddings.dim() > 2:
    speaker_embeddings = speaker_embeddings.squeeze()  # Elimina dimensiones extra
if speaker_embeddings.dim() == 1:
    speaker_embeddings = speaker_embeddings.unsqueeze(0)

# Generar audio
texto = "Esto es un texto generado usando embeddings promedio."
text_to_speech(text=texto, processor=processor, model=model, vocoder=vocoder, speaker_embeddings=speaker_embeddings, output_file="./audio_generado_mozilla-promedio.wav")


INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch custom.py: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch embedding_model.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch mean_var_norm_emb.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch classifier.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch label_encoder.txt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.parameter_transfer:Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder
Reading metadata...: 15520it [00:00, 51117.75it

Audio guardado en ./audio_generado_mozilla-promedio.wav


tensor([[-2.3121e-05,  2.7067e-05, -3.5930e-06,  ..., -1.0116e-04,
         -1.2247e-05,  2.2230e-06]])

#### Tarea TTSB2

Con lo visto en el notebook, ¿Cómo podríamos generar un sistema TTS que sonara como otra persona?